# Generated by Django 3.0.3 on 2020-03-02 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='Module Code')),
                ('name', models.CharField(max_length=50, verbose_name='Module Code')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='Professor Code')),
                ('name', models.CharField(max_length=50, verbose_name='Professor Name')),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('noOfRatings', models.IntegerField()),
                ('moduleCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rater.Module')),
                ('profCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rater.Professor')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='teachers',
            field=models.ManyToManyField(to='rater.Professor'),
        ),
    ]
