# Generated by Django 3.0.3 on 2020-03-03 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, verbose_name='Account Name')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('account', models.ManyToManyField(to='rater.Account')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rater.Instance')),
            ],
        ),
        migrations.RemoveField(
            model_name='module',
            name='teachers',
        ),
        migrations.DeleteModel(
            name='Ratings',
        ),
        migrations.AddField(
            model_name='instance',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rater.Module'),
        ),
        migrations.AddField(
            model_name='instance',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rater.Professor'),
        ),
    ]
