# Generated by Django 3.0.3 on 2020-03-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0003_auto_20200304_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='semester',
            field=models.IntegerField(default=1, verbose_name='semester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instance',
            name='year',
            field=models.IntegerField(default=2019, verbose_name='Year'),
            preserve_default=False,
        ),
    ]
