# Generated by Django 2.2.7 on 2020-03-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0005_auto_20200311_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(max_length=3, unique=True, verbose_name='Module Code'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='code',
            field=models.CharField(max_length=3, unique=True, verbose_name='Professor Code'),
        ),
    ]
