# Generated by Django 2.2.7 on 2020-03-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0006_auto_20200311_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Module Name'),
        ),
    ]
